parameters:
    avtonom_semaphore.try_count: 240 # try count, if lock not acquired. 240 count * 1/2 seconds (sleep wait) = 120 sec wait
    avtonom_semaphore.sleep_time: 500000 # sleep time in microseconds, if lock not acquired. 1.000.000 microseconds = 1 seconds
    avtonom_semaphore.max_lock_time: 60 # ttl - max_lock_time
    avtonom_semaphore.prefix: 'lock_' # prefix to key

services:
    avtonom_semaphore.key_storage:
        public: false
        class: "%avtonom_semaphore.key_storage_class%"

    avtonom_semaphore.logger_handler:
        public: false
        class: Monolog\Handler\RotatingFileHandler
        arguments: ["%kernel.logs_dir%/%kernel.environment%.semaphore.log"]

    avtonom_semaphore.logger:
        public: false
        class: Symfony\Bridge\Monolog\Logger
        arguments: ["semaphore"]
        calls:
            - [pushHandler, ["@avtonom_semaphore.logger_handler"]]

    avtonom_semaphore.manager:
        class: "%avtonom_semaphore.manager_class%"
        arguments:
            - "%avtonom_semaphore.adapter%"
            - "@avtonom_semaphore.key_storage"
            - "%avtonom_semaphore.try_count%"
            - "%avtonom_semaphore.sleep_time%"
            - "%avtonom_semaphore.max_lock_time%"
            - "%avtonom_semaphore.is_exception_repeat_block_key%"
            - "%avtonom_semaphore.use_extended_methods%"
            - "%avtonom_semaphore.prefix%"
            - "@avtonom_semaphore.logger"
            - "%avtonom_semaphore.mode%"
